
name: PR - Automations Testes Clients APP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x]

      # Checkout  do codigo do projeto
      - name: Checkout
        uses: actions/checkout@v2 

      # Setup do Node.JS
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
    
      # Dependecies install
      - name: Install dependecies
        run: npm install
      
      # Regression test execute
      - uses: microsoft/playwright-github-action@v1
      - name: run CodeceptJS tests
        run: npx codeceptjs run

          