
name: PR - Automations Testes Clients APP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2 

      # - name: Setup Node.js environment
      #   uses: actions/setup-node@v2.2.0
      #   with:
      #     node-version: ${{ matrix.node-version }}

      - name: Setup Node
        uses: actions/setup-node@v1
    
      - name: Install dependecies
        run: | 
          npm install
      
      - name: Setup Playwright    
        uses: microsoft/playwright-github-action@v1

      - name: run CodeceptJS tests
        run: npx codeceptjs run

          